language: node_js
node_js:
  - node
install:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
deploy:
  on:
    branch: master
  provider: s3
  bucket: $S3_BUCKET_NAME 
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  region: $S3_ENDPOINT
  acl: public_read
after_deploy:
  - export AWS_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$S3_SECRET_KEY
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
