language: node_js
node_js:
  - node
deploy:
  on:
    branch: master
  provider: s3
  bucket: $S3_BUCKET_NAME 
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  region: $S3_ENDPOINT
  acl: public_read